stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build
  only:
    - master
  script:
    - echo "---hello build---"

deploy:
  stage: deploy
  tags:
    - build
  only:
    - master
  script:
    - echo "---hello deploy---"