server:
  port: 8402
spring:
  rabbitmq:
    host: 101.132.143.228
    port: 5672
    userName: guest
    password: guest
    virtualhost: /
  redis:
    host: 101.132.143.228
    password: 123456
  main:
    allow-bean-definition-overriding: true
  application:
    name: local-service-socket
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/uep?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      max-active: 200
      filter:
        config:
          enabled: true
mybatis-plus:
  mapper-locations: classpath*:com/yuqijun/socket/dao/*Mapper.xml
app:
  id: ${spring.application.name}
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    namespaces: application
    enabled: false
    eagerLoad.enabled: false
eureka:
  client:
    enabled: false
  cors:
    enabled: treu
  internal-agent:
    enabled: false
logging:
  level:
    root: info # 根日志，默认级别是info，如果使用info，可以不写这一行
    com.moyundong.dao: debug # 子级别日志，可以指定到自己的某个包
  file: /Users/yuqijun/yuqijun/local-service-log/log # 定义日志文件的路径，可以是相对路径也可以是绝对路径